name: Extract and Commit Customizations

env:
  clientId: ${{ secrets.APIMAUTOMATIONIDENTITYCLIENTID }}
  password: ${{ secrets.APIMAUTOMATIONIDENTITYCLIENTSECRET }}
  tenant: ${{ secrets.APIMAUTOMATIONIDENTITYTENANTID }}
  apimName: ${{ secrets.APIMNAMEDEV }}
  resourceGroup: ${{ secrets.RESOURCEGROUPNAMEDEV }}

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'Branch name to commit changes'
        required: false
        default: 'feature/update'

jobs:
  extract_and_commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup PowerShell
        uses: actions/setup-powershell@v2

      - name: Extract APIM Customizations
        run: |
          pwsh -Command "./Export-APIMDeveloperPortal.ps1 -ClientId '${{ env.clientId }}' -ClientSecret '${{ env.password }}' -TenantId '${{ env.tenant }}' -ApimName '${{ env.apimName }}' -ResourceGroup '${{ env.resourceGroup }}'"
        shell: bash

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Determine Branch Name
        id: branch
        run: |
          BRANCH_NAME="${{ github.event.inputs.branch_name }}-${{ github.run_number }}"
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
          echo "::set-output name=branch_name::$BRANCH_NAME"

      - name: Create New Branch
        run: |
          git fetch
          git checkout -b ${{ steps.branch.outputs.branch_name }}

      - name: Commit changes
        run: |
          git add .
          git commit -m "Extracted APIM customizations"
          if [ "$(git status --porcelain)" != "" ]; then
            git push origin ${{ steps.branch.outputs.branch_name }}
          else
            echo "No changes to commit."
          fi
        shell: bash
