name: Extract and Commit Customizations

env:
  clientId: ${{ secrets.APIMAUTOMATIONIDENTITYCLIENTID }}
  password: ${{ secrets.APIMAUTOMATIONIDENTITYCLIENTSECRET }}
  tenant: ${{ secrets.APIMAUTOMATIONIDENTITYTENANTID }}
  apimName: ${{ secrets.APIMNAMEDEV }}
  resourceGroup: ${{ secrets.RESOURCEGROUPNAMEDEV }}

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'Branch name to commit changes'
        required: true
        default: 'feature/update-${{ github.run_number }}'

jobs:
  extract_and_commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup PowerShell
        uses: actions/setup-powershell@v2

      - name: Extract APIM Customizations
        run: |
          pwsh -Command "./Export-APIMDeveloperPortal.ps1 -ExportFolder Export -AppId '${{ env.clientId }}' -Secret '${{ env.password }}' -Tenant '${{ env.tenant }}' -APIMName '${{ env.apimName }}' -ResourceGroupName '${{ env.resourceGroup }}'"
        shell: bash

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Create New Branch
        run: |
          git fetch
          git checkout -b ${{ github.event.inputs.branch_name }}

      - name: Commit changes
        run: |
          git add .
          git commit -m "Extracted APIM customizations"
          if [ "$(git status --porcelain)" != "" ]; then
            git push origin ${{ github.event.inputs.branch_name }}
          else
            echo "No changes to commit."
          fi
        shell: bash
