name: Publish APIM Developer Portal Content

on:
  push:
    branches:
      - 'main'  # This should trigger the workflow when any branch matching the pattern is pushed.

jobs:
  import_apim_content:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensures we fetch all history for all branches and tags.

      - name: Setup PowerShell
        run: |
          sudo apt-get update
          sudo apt-get install -y powershell
        shell: bash

      - name: Install Azure PowerShell module
        run: |
          pwsh -Command "Install-Module -Name Az -AllowClobber -Scope CurrentUser -Force"
        shell: pwsh

      - name: Copy Extract to Publish
        run: |
          mkdir -p Publish
          cp -r developerPortalScripts/Extract/* developerPortalScripts/Publish/
        shell: bash

      - name: Execute Import PowerShell Script
        run: |
          pwsh -Command "./developerPortalScripts/publishDeveloperPortal.ps1 -ResourceGroupName '${{ secrets.RESOURCEGROUPNAMEPROD }}' -APIMName '${{ secrets.APIMNAMEPROD }}' -ImportFolder './developerPortalScripts/Publish' -AppId '${{ secrets.APIMAUTOMATIONIDENTITYCLIENTID }}' -Secret '${{ secrets.APIMAUTOMATIONIDENTITYCLIENTSECRET }}' -Tenant '${{ secrets.APIMAUTOMATIONIDENTITYTENANTID }}'"
        shell: pwsh
